---
- hosts: webservers
  remote_user: ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Apache latest version installation
    yum:
      name: httpd
      state: latest
  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
